source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'

target 'ZFPlayer_Example' do
    pod 'FDFullscreenPopGesture'
    pod 'MJRefresh'
    pod 'ZFPlayer', :path => '../'
     pod  'ijkmediaframeworkedit',:git=>'http://gitlab.umer.com.cn/nangua/ijkmediaframeworkedit.git'
end
